{% set version = "0.1.7" %}
{% set url_base = "https://github.com/lab-cosmo/metatensor/releases/download" %}

package:
  name: libmetatensor
  version: {{ version }}

source:
  url: {{ url_base }}/metatensor-core-v{{ version }}/metatensor-core-cxx-{{ version }}.tar.gz
  sha256: 005c39aefdd5aaf8a7596b78ac01688976070795c4db21e20e6b8db4f2421e97

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - cargo-bundle-licenses

test:
  commands:
    - test -f $PREFIX/lib/libmetatensor$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\metatensor.dll exit 1  # [win]

about:
  home: https://github.com/lab-cosmo/metatensor
  summary: 'Self-describing sparse tensor data format for atomistic machine learning and beyond'
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  doc_url: https://lab-cosmo.github.io/metatensor/

extra:
  recipe-maintainers:
    - Luthaf
    - PicoCentauri
