{% set version = "0.1.18" %}
{% set url_base = "https://github.com/lab-cosmo/metatensor/releases/download" %}

package:
  name: libmetatensor
  version: {{ version }}

source:
  url: {{ url_base }}/metatensor-core-v{{ version }}/metatensor-core-cxx-{{ version }}.tar.gz
  sha256: 617680f86751826221f7738f30e66cda350dd8f79725aba2b0c25df91d0d8614

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libmetatensor', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - cargo-bundle-licenses

test:
  requires:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
  files:
    - test-project/
  commands:
    - test -f $PREFIX/lib/libmetatensor$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\metatensor.dll exit 1  # [win]
    - cmake -G Ninja -S test-project -B test-project
    - cmake --build test-project
    - ctest --verbose --test-dir test-project

about:
  home: https://github.com/metatensor/metatensor
  summary: 'Self-describing sparse tensor data format for atomistic machine learning and beyond'
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  doc_url: https://docs.metatensor.org

extra:
  recipe-maintainers:
    - HaoZeke
    - Luthaf
    - PicoCentauri
